fragment ProductImageFields on Image {
  id
  url
  altText
  width
  height
}

fragment ProductFields on Product {
  id
  title
  handle
  createdAt
  descriptionHtml
  images(first: $imagesFirst) {
    edges {
      node {
        ...ProductImageFields
      }
    }
  }
  priceRange {
    maxVariantPrice {
      amount
      currencyCode
    }
  }
  artist: metafield(namespace: "custom", key: "artist") {
    value
    type
  }
  category: metafield(namespace: "custom", key: "category") {
    value
    type
  }
  dimensionsImperial: metafield(namespace: "custom", key: "dimensions_us") {
    value
    type
  }
  dimensionsMetric: metafield(namespace: "custom", key: "dimensions_global") {
    value
    type
  }
  medium: metafield(namespace: "custom", key: "medium") {
    value
    type
  }
  style: metafield(namespace: "shopify", key: "art-movement") {
    references(first: 4) {
      nodes {
        __typename
        ...LabeledMetaobject
      }
    }
  }
  theme: metafield(namespace: "shopify", key: "theme") {
    references(first: 4) {
      nodes {
        __typename
        ...LabeledMetaobject
      }
    }
  }
}

query Public_GetAllProducts(
  $first: Int = 24
  $after: String
  $sortKey: ProductSortKeys = TITLE
  $reverse: Boolean = false
  $imagesFirst: Int = 1
) {
  products(first: $first, after: $after, sortKey: $sortKey, reverse: $reverse) {
    pageInfo {
      hasNextPage
      endCursor
    }
    edges {
      cursor
      node {
        ...ProductFields
      }
    }
  }
}

query Public_GetCollectionProducts(
  $collectionHandle: String!
  $productsFirst: Int = 12
  $productsAfter: String
  $imagesFirst: Int = 1
) {
  collectionByHandle(handle: $collectionHandle) {
    products(first: $productsFirst, after: $productsAfter) {
      pageInfo {
        hasNextPage
        endCursor
      }
      edges {
        cursor
        node {
          ...ProductFields
        }
      }
    }
  }
}

# Fetch a single product by handle (for detail pages)
query Public_GetProductByHandle($handle: String!, $imagesFirst: Int = 6) {
  productByHandle(handle: $handle) {
    ...ProductFields
  }
}

query GetProductsForCheckout($ids: [ID!]!) {
  products: nodes(ids: $ids) {
    __typename
    ... on Product {
      id
      handle
      title
      availableForSale
      variants(first: 1) {
        edges {
          node {
            id
            availableForSale
            quantityAvailable
            price {
              amount
              currencyCode
            }
          }
        }
      }
    }
  }
}
