/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PathlessLayoutRouteRouteImport } from './routes/_pathlessLayout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PathlessLayoutAboutRouteRouteImport } from './routes/_pathlessLayout/about/route'
import { Route as PathlessLayoutMagazineIndexRouteImport } from './routes/_pathlessLayout/magazine/index'
import { Route as PathlessLayoutEventsIndexRouteImport } from './routes/_pathlessLayout/events/index'
import { Route as PathlessLayoutArtworksIndexRouteImport } from './routes/_pathlessLayout/artworks/index'
import { Route as PathlessLayoutArtistsIndexRouteImport } from './routes/_pathlessLayout/artists/index'
import { Route as PathlessLayoutAboutIndexRouteImport } from './routes/_pathlessLayout/about/index'
import { Route as ApiShopifyGraphqlRouteImport } from './routes/api/shopify/graphql'
import { Route as PathlessLayoutArtworksSlugIndexRouteImport } from './routes/_pathlessLayout/artworks/$slug.index'
import { Route as PathlessLayoutArtistsSlugIndexRouteImport } from './routes/_pathlessLayout/artists/$slug/index'
import { Route as PathlessLayoutEventsFairsSlugIndexRouteImport } from './routes/_pathlessLayout/events/fairs/$slug.index'
import { Route as PathlessLayoutEventsExhibitionsSlugIndexRouteImport } from './routes/_pathlessLayout/events/exhibitions/$slug.index'

const PathlessLayoutRouteRoute = PathlessLayoutRouteRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutAboutRouteRoute =
  PathlessLayoutAboutRouteRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)
const PathlessLayoutMagazineIndexRoute =
  PathlessLayoutMagazineIndexRouteImport.update({
    id: '/magazine/',
    path: '/magazine/',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)
const PathlessLayoutEventsIndexRoute =
  PathlessLayoutEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)
const PathlessLayoutArtworksIndexRoute =
  PathlessLayoutArtworksIndexRouteImport.update({
    id: '/artworks/',
    path: '/artworks/',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)
const PathlessLayoutArtistsIndexRoute =
  PathlessLayoutArtistsIndexRouteImport.update({
    id: '/artists/',
    path: '/artists/',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)
const PathlessLayoutAboutIndexRoute =
  PathlessLayoutAboutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PathlessLayoutAboutRouteRoute,
  } as any)
const ApiShopifyGraphqlRoute = ApiShopifyGraphqlRouteImport.update({
  id: '/api/shopify/graphql',
  path: '/api/shopify/graphql',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutArtworksSlugIndexRoute =
  PathlessLayoutArtworksSlugIndexRouteImport.update({
    id: '/artworks/$slug/',
    path: '/artworks/$slug/',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)
const PathlessLayoutArtistsSlugIndexRoute =
  PathlessLayoutArtistsSlugIndexRouteImport.update({
    id: '/artists/$slug/',
    path: '/artists/$slug/',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)
const PathlessLayoutEventsFairsSlugIndexRoute =
  PathlessLayoutEventsFairsSlugIndexRouteImport.update({
    id: '/events/fairs/$slug/',
    path: '/events/fairs/$slug/',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)
const PathlessLayoutEventsExhibitionsSlugIndexRoute =
  PathlessLayoutEventsExhibitionsSlugIndexRouteImport.update({
    id: '/events/exhibitions/$slug/',
    path: '/events/exhibitions/$slug/',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof PathlessLayoutAboutRouteRouteWithChildren
  '/api/shopify/graphql': typeof ApiShopifyGraphqlRoute
  '/about/': typeof PathlessLayoutAboutIndexRoute
  '/artists': typeof PathlessLayoutArtistsIndexRoute
  '/artworks': typeof PathlessLayoutArtworksIndexRoute
  '/events': typeof PathlessLayoutEventsIndexRoute
  '/magazine': typeof PathlessLayoutMagazineIndexRoute
  '/artists/$slug': typeof PathlessLayoutArtistsSlugIndexRoute
  '/artworks/$slug': typeof PathlessLayoutArtworksSlugIndexRoute
  '/events/exhibitions/$slug': typeof PathlessLayoutEventsExhibitionsSlugIndexRoute
  '/events/fairs/$slug': typeof PathlessLayoutEventsFairsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/shopify/graphql': typeof ApiShopifyGraphqlRoute
  '/about': typeof PathlessLayoutAboutIndexRoute
  '/artists': typeof PathlessLayoutArtistsIndexRoute
  '/artworks': typeof PathlessLayoutArtworksIndexRoute
  '/events': typeof PathlessLayoutEventsIndexRoute
  '/magazine': typeof PathlessLayoutMagazineIndexRoute
  '/artists/$slug': typeof PathlessLayoutArtistsSlugIndexRoute
  '/artworks/$slug': typeof PathlessLayoutArtworksSlugIndexRoute
  '/events/exhibitions/$slug': typeof PathlessLayoutEventsExhibitionsSlugIndexRoute
  '/events/fairs/$slug': typeof PathlessLayoutEventsFairsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pathlessLayout': typeof PathlessLayoutRouteRouteWithChildren
  '/_pathlessLayout/about': typeof PathlessLayoutAboutRouteRouteWithChildren
  '/api/shopify/graphql': typeof ApiShopifyGraphqlRoute
  '/_pathlessLayout/about/': typeof PathlessLayoutAboutIndexRoute
  '/_pathlessLayout/artists/': typeof PathlessLayoutArtistsIndexRoute
  '/_pathlessLayout/artworks/': typeof PathlessLayoutArtworksIndexRoute
  '/_pathlessLayout/events/': typeof PathlessLayoutEventsIndexRoute
  '/_pathlessLayout/magazine/': typeof PathlessLayoutMagazineIndexRoute
  '/_pathlessLayout/artists/$slug/': typeof PathlessLayoutArtistsSlugIndexRoute
  '/_pathlessLayout/artworks/$slug/': typeof PathlessLayoutArtworksSlugIndexRoute
  '/_pathlessLayout/events/exhibitions/$slug/': typeof PathlessLayoutEventsExhibitionsSlugIndexRoute
  '/_pathlessLayout/events/fairs/$slug/': typeof PathlessLayoutEventsFairsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api/shopify/graphql'
    | '/about/'
    | '/artists'
    | '/artworks'
    | '/events'
    | '/magazine'
    | '/artists/$slug'
    | '/artworks/$slug'
    | '/events/exhibitions/$slug'
    | '/events/fairs/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/shopify/graphql'
    | '/about'
    | '/artists'
    | '/artworks'
    | '/events'
    | '/magazine'
    | '/artists/$slug'
    | '/artworks/$slug'
    | '/events/exhibitions/$slug'
    | '/events/fairs/$slug'
  id:
    | '__root__'
    | '/'
    | '/_pathlessLayout'
    | '/_pathlessLayout/about'
    | '/api/shopify/graphql'
    | '/_pathlessLayout/about/'
    | '/_pathlessLayout/artists/'
    | '/_pathlessLayout/artworks/'
    | '/_pathlessLayout/events/'
    | '/_pathlessLayout/magazine/'
    | '/_pathlessLayout/artists/$slug/'
    | '/_pathlessLayout/artworks/$slug/'
    | '/_pathlessLayout/events/exhibitions/$slug/'
    | '/_pathlessLayout/events/fairs/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathlessLayoutRouteRoute: typeof PathlessLayoutRouteRouteWithChildren
  ApiShopifyGraphqlRoute: typeof ApiShopifyGraphqlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/about': {
      id: '/_pathlessLayout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PathlessLayoutAboutRouteRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/magazine/': {
      id: '/_pathlessLayout/magazine/'
      path: '/magazine'
      fullPath: '/magazine'
      preLoaderRoute: typeof PathlessLayoutMagazineIndexRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/events/': {
      id: '/_pathlessLayout/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof PathlessLayoutEventsIndexRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/artworks/': {
      id: '/_pathlessLayout/artworks/'
      path: '/artworks'
      fullPath: '/artworks'
      preLoaderRoute: typeof PathlessLayoutArtworksIndexRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/artists/': {
      id: '/_pathlessLayout/artists/'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof PathlessLayoutArtistsIndexRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/about/': {
      id: '/_pathlessLayout/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof PathlessLayoutAboutIndexRouteImport
      parentRoute: typeof PathlessLayoutAboutRouteRoute
    }
    '/api/shopify/graphql': {
      id: '/api/shopify/graphql'
      path: '/api/shopify/graphql'
      fullPath: '/api/shopify/graphql'
      preLoaderRoute: typeof ApiShopifyGraphqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/artworks/$slug/': {
      id: '/_pathlessLayout/artworks/$slug/'
      path: '/artworks/$slug'
      fullPath: '/artworks/$slug'
      preLoaderRoute: typeof PathlessLayoutArtworksSlugIndexRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/artists/$slug/': {
      id: '/_pathlessLayout/artists/$slug/'
      path: '/artists/$slug'
      fullPath: '/artists/$slug'
      preLoaderRoute: typeof PathlessLayoutArtistsSlugIndexRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/events/fairs/$slug/': {
      id: '/_pathlessLayout/events/fairs/$slug/'
      path: '/events/fairs/$slug'
      fullPath: '/events/fairs/$slug'
      preLoaderRoute: typeof PathlessLayoutEventsFairsSlugIndexRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/events/exhibitions/$slug/': {
      id: '/_pathlessLayout/events/exhibitions/$slug/'
      path: '/events/exhibitions/$slug'
      fullPath: '/events/exhibitions/$slug'
      preLoaderRoute: typeof PathlessLayoutEventsExhibitionsSlugIndexRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
  }
}

interface PathlessLayoutAboutRouteRouteChildren {
  PathlessLayoutAboutIndexRoute: typeof PathlessLayoutAboutIndexRoute
}

const PathlessLayoutAboutRouteRouteChildren: PathlessLayoutAboutRouteRouteChildren =
  {
    PathlessLayoutAboutIndexRoute: PathlessLayoutAboutIndexRoute,
  }

const PathlessLayoutAboutRouteRouteWithChildren =
  PathlessLayoutAboutRouteRoute._addFileChildren(
    PathlessLayoutAboutRouteRouteChildren,
  )

interface PathlessLayoutRouteRouteChildren {
  PathlessLayoutAboutRouteRoute: typeof PathlessLayoutAboutRouteRouteWithChildren
  PathlessLayoutArtistsIndexRoute: typeof PathlessLayoutArtistsIndexRoute
  PathlessLayoutArtworksIndexRoute: typeof PathlessLayoutArtworksIndexRoute
  PathlessLayoutEventsIndexRoute: typeof PathlessLayoutEventsIndexRoute
  PathlessLayoutMagazineIndexRoute: typeof PathlessLayoutMagazineIndexRoute
  PathlessLayoutArtistsSlugIndexRoute: typeof PathlessLayoutArtistsSlugIndexRoute
  PathlessLayoutArtworksSlugIndexRoute: typeof PathlessLayoutArtworksSlugIndexRoute
  PathlessLayoutEventsExhibitionsSlugIndexRoute: typeof PathlessLayoutEventsExhibitionsSlugIndexRoute
  PathlessLayoutEventsFairsSlugIndexRoute: typeof PathlessLayoutEventsFairsSlugIndexRoute
}

const PathlessLayoutRouteRouteChildren: PathlessLayoutRouteRouteChildren = {
  PathlessLayoutAboutRouteRoute: PathlessLayoutAboutRouteRouteWithChildren,
  PathlessLayoutArtistsIndexRoute: PathlessLayoutArtistsIndexRoute,
  PathlessLayoutArtworksIndexRoute: PathlessLayoutArtworksIndexRoute,
  PathlessLayoutEventsIndexRoute: PathlessLayoutEventsIndexRoute,
  PathlessLayoutMagazineIndexRoute: PathlessLayoutMagazineIndexRoute,
  PathlessLayoutArtistsSlugIndexRoute: PathlessLayoutArtistsSlugIndexRoute,
  PathlessLayoutArtworksSlugIndexRoute: PathlessLayoutArtworksSlugIndexRoute,
  PathlessLayoutEventsExhibitionsSlugIndexRoute:
    PathlessLayoutEventsExhibitionsSlugIndexRoute,
  PathlessLayoutEventsFairsSlugIndexRoute:
    PathlessLayoutEventsFairsSlugIndexRoute,
}

const PathlessLayoutRouteRouteWithChildren =
  PathlessLayoutRouteRoute._addFileChildren(PathlessLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathlessLayoutRouteRoute: PathlessLayoutRouteRouteWithChildren,
  ApiShopifyGraphqlRoute: ApiShopifyGraphqlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
