# Uses Shopify's blog feature to create artist bios

query Public_GetFeaturedArtists {
  blog(handle: "artist") {
    articles(first: 4, query: "tag:'featured'") {
      edges {
        node {
          id
          title
          handle
          contentHtml
          image {
            url
          }
        }
      }
    }
  }
}
